[package]
name = "voicecode"
version = "0.1.0"
authors = ["Chris Given <chris.given@moonlightcompanies.com>"]
description = "VoiceCode calculator for Produce Traceability Initiative"
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.31"
regex = "1.10.2"
lazy_static = "1.4.0"